on: [push]

jobs:
  Notion_Hook_job:
    runs-on: ubuntu-latest
    name: A job to connect to Notion
    steps:
      - name: Connect to Notion step
        id: notion
        uses: alessandrobelli/notion-hook@v1.0
        with:
          notion_secret: ${{ secrets.NOTION_SECRET }}
          notion_database: ${{ secrets.NOTION_DATABASE }}

